:page-partial:

[[support]]
= Support

For troubleshooting, have a look at the xref:support/known-issues.adoc#known-issues[known issues] and the xref:support/known-limitations.adoc#known-limitations[known limitations] of the Aspect Model Editor.

As the Aspect Model Editor relies on the SAMM specification, also check out the https://eclipse-esmf.github.io/samm-specification/2.0.0/index.html[SAMM Aspect Meta Model version 2.0.0^,opts=nofollow].

For further support, open an https://github.com/eclipse-esmf/esmf-aspect-model-editor/issues[issue in GitHub^,opts=nofollow].
To enable the community to give you the best possible advice, please include the following to your issue:

* Procedure you worked on when you experienced the unexpected behavior.
* Expected behavior.
* Description of the discovered behavior.
* Version of the Aspect Model Editor you use.
* Additional helpful resources (screenshots, TTL files, etc.).

For general questions on semantic data structuring and the role of the Aspect Model Editor, discuss within the working groups of the https://www.eclipse.org/forums/index.php/f/617/[Eclipse Community Forums^,opts=nofollow].

++++
<style>
  .imageblock {flex-direction: row !important;}
</style>
++++
