; Copyright (c) 2026 Robert Bosch Manufacturing Solutions GmbH
;
; See the AUTHORS file(s) distributed with this work for
; additional information regarding authorship.
;
; This Source Code Form is subject to the terms of the Mozilla Public
; License, v. 2.0. If a copy of the MPL was not distributed with this
; file, You can obtain one at https://mozilla.org/MPL/2.0/.
;
; SPDX-License-Identifier: MPL-2.0

; Hooks for the NSIS installer generated by Tauri (see bundle > windows > nsis > installerHooks).

!define LEGACY_PRODUCT_KEY "Software\ASPECT-MODEL-EDITOR"
!define LEGACY_UNINSTALL_KEY "SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\ASPECT-MODEL-EDITOR"

!macro NSIS_HOOK_PREINSTALL
  ; Remove an installation created by the former custom installer (win-installer/installer.nsi),
  ; which used its own registry keys and is therefore not detected by the Tauri installer.
  Push $R0
  Push $R1
  ReadRegStr $R0 HKLM "${LEGACY_UNINSTALL_KEY}" "UninstallString"
  ReadRegStr $R1 HKCU "${LEGACY_PRODUCT_KEY}" ""
  ${If} $R0 != ""
  ${AndIf} $R1 != ""
  ${AndIf} ${FileExists} "$R1\Uninstall.exe"
    DetailPrint "Removing previous Aspect Model Editor installation in $R1"
    ; The legacy uninstaller requires elevation, so ShellExecute is needed to show the UAC prompt.
    ; "_?=" makes it run in place and wait until it has finished.
    ExecShellWait "open" "$R1\Uninstall.exe" "/S _?=$R1"
    Delete "$R1\Uninstall.exe"
    RMDir "$R1"
  ${EndIf}
  Pop $R1
  Pop $R0

  ; The backend folder carries the version in its name and the app starts the first backend it finds.
  ; Remove the backend of a previous version, so an update never keeps or starts it.
  RMDir /r "$INSTDIR\backend"
!macroend

!macro NSIS_HOOK_POSTUNINSTALL
  ; Tauri only deletes the files of the installed version and keeps the folder if anything else is left
  ; (e.g. the backend of an older version). Remove the whole folder, but only if it is the app's own folder,
  ; so a user-chosen folder like "C:\Tools" is never deleted completely.
  Push $R0
  ${GetFileName} "$INSTDIR" $R0
  ${If} $R0 == "${PRODUCTNAME}"
    RMDir /r /REBOOTOK "$INSTDIR"
  ${EndIf}
  Pop $R0
!macroend

!macro NSIS_HOOK_POSTINSTALL
  ; Default workspace for the user's Aspect Models
  CreateDirectory "$PROFILE\aspect-model-editor\models"
!macroend
