export enum PropertyEnum {
  Name = 'name',
  See = 'see',
  PreferredName = 'preferredName',
  Description = 'description',
  DataType = 'dataType',
  Optional = 'optional',
  MinValue = 'minValue',
  MaxValue = 'maxValue',
  Integer = 'integer',
  Scale = 'scale',
  Value = 'value',
  NotInPayload = 'notInPayload',
  LocaleCode = 'localeCode',
  LanguageCode = 'languageCode',
  LowerBoundDefinition = 'lowerBoundDefinition',
  UpperBoundDefinition = 'upperBoundDefinition',
  Code = 'code',
  Symbol = 'symbol',
  CommonCode = 'commonCode',
  ConversionFactor = 'conversionFactor',
  NumericConversionFactor = 'numericConversionFactor',
}
