/*
 * Copyright (c) 2026 Robert Bosch Manufacturing Solutions GmbH
 *
 * See the AUTHORS file(s) distributed with this work for
 * additional information regarding authorship.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * SPDX-License-Identifier: MPL-2.0
 */

export const EVENTS = {
  REQUEST: {
    CREATE_WINDOW: 'CREATE_WINDOW',
    IS_FIRST_WINDOW: 'IS_FIRST_WINDOW',
    WINDOW_DATA: 'WINDOW_DATA',
    UPDATE_DATA: 'UPDATE_DATA',
    MAXIMIZE_WINDOW: 'MAXIMIZE_WINDOW',
    IS_FILE_SAVED: 'IS_FILE_SAVED',
    CLOSE_WINDOW: 'CLOSE_WINDOW',
    SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
    EDIT_ELEMENT: 'EDIT_ELEMENT',
    REFRESH_WORKSPACE: 'REFRESH_WORKSPACE',
  },
  RESPONSE: {
    IS_FIRST_WINDOW: 'IS_FIRST_WINDOW',
    BACKEND_STARTUP_ERROR: 'BACKEND_STARTUP_ERROR',
    WINDOW_DATA: 'WINDOW_DATA',
  },
  SIGNAL: {
    REFRESH_WORKSPACE: 'REFRESH_WORKSPACE',
    WINDOW_FOCUS: 'WINDOW_FOCUS',
    NEW_EMPTY_MODEL: 'NEW_EMPTY_MODEL',
    LOAD_FILE: 'LOAD_FILE',
    LOAD_FROM_TEXT: 'LOAD_FROM_TEXT',
    LOAD_SPECIFIC_FILE: 'LOAD_SPECIFIC_FILE',
    NEW_WINDOW: 'NEW_WINDOW',
    IMPORT_TO_WORKSPACE: 'IMPORT_TO_WORKSPACE',
    IMPORT_NAMESPACES: 'IMPORT_NAMESPACES',
    COPY_TO_CLIPBOARD: 'COPY_TO_CLIPBOARD',
    SAVE_TO_WORKSPACE: 'SAVE_TO_WORKSPACE',
    EXPORT_MODEL: 'EXPORT_MODEL',
    EXPORT_NAMESPACES: 'EXPORT_NAMESPACES',
    SHOW_HIDE_TOOLBAR: 'SHOW_HIDE_TOOLBAR',
    SHOW_HIDE_MINIMAP: 'SHOW_HIDE_MINIMAP',
    FILTER_MODEL_BY: 'FILTER_MODEL_BY',
    ZOOM_IN: 'ZOOM_IN',
    ZOOM_OUT: 'ZOOM_OUT',
    ZOOM_TO_FIT: 'ZOOM_TO_FIT',
    ZOOM_TO_ACTUAL: 'ZOOM_TO_ACTUAL',
    OPEN_SELECTED_ELEMENT: 'OPEN_SELECTED_ELEMENT',
    REMOVE_SELECTED_ELEMENT: 'REMOVE_SELECTED_ELEMENT',
    COLLAPSE_EXPAND_MODEL: 'COLLAPSE_EXPAND_MODEL',
    FORMAT_MODEL: 'FORMAT_MODEL',
    CONNECT_ELEMENTS: 'CONNECT_ELEMENTS',
    SEARCH_ELEMENT: 'SEARCH_ELEMENT',
    SEARCH_ELEMENTS: 'SEARCH_ELEMENTS',
    VALIDATE_MODEL: 'VALIDATE_MODEL',
    GENERATE_HTML_DOCUMENTATION: 'GENERATE_HTML_DOCUMENTATION',
    GENERATE_OPEN_API_SPECIFICATION: 'GENERATE_OPEN_API_SPECIFICATION',
    GENERATE_ASYNC_API_SPECIFICATION: 'GENERATE_ASYNC_API_SPECIFICATION',
    GENERATE_AASX_XML: 'GENERATE_AASX_XML',
    GENERATE_JSON_PAYLOAD: 'GENERATE_JSON_PAYLOAD',
    GENERATE_JSON_SCHEMA: 'GENERATE_JSON_SCHEMA',
    SEARCH_FILES: 'SEARCH_FILES',
    UPDATE_MENU_ITEM: 'UPDATE_MENU_ITEM',
    TRANSLATE_MENU_ITEMS: 'TRANSLATE_MENU_ITEMS',
  },
} as const;

export type EventKey = keyof typeof EVENTS;
